name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          check-latest: true
          cache: 'yarn'
          node-version-file: '.tool-versions'

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: FE build cache cache
        uses: actions/cache@v4
        with:
          path: |
            tmp/cache
          key: ${{ runner.os }}-builder-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-builder-cache-

      - name: Check linters
        run: yarn run lint

      - name: Check tests
        run: yarn run test

      - name: Build website
        run: bundle exec middleman build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/"

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
